#include "rgb.h"

void rgbInitialize() {
	
	SIM->SCGC5 |= SIM_SCGC5_PORTB_MASK;
	SIM->SCGC6 |= SIM_SCGC6_TPM1_MASK;
	SIM->SCGC6 |= SIM_SCGC6_TPM2_MASK;
	SIM->SOPT2 |= SIM_SOPT2_TPMSRC(1);
	SIM->SOPT2 |= SIM_SOPT2_PLLFLLSEL_MASK;
	TPM1->SC &= ~TPM_SC_CPWMS_MASK;
	TPM1->SC |= TPM_SC_PS(7);
	TPM1->MOD = 255;
	TPM2->SC &= ~TPM_SC_CPWMS_MASK;
	TPM2->SC |= TPM_SC_PS(7);
	TPM2->MOD = 255;
	TPM1->CONTROLS[0].CnSC |= (TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK);
	TPM1->CONTROLS[0].CnSC &= ~(TPM_CnSC_MSA_MASK | TPM_CnSC_ELSB_MASK);
	TPM1->CONTROLS[0].CnV = 0;
	PORTB->PCR[0] |= PORT_PCR_MUX(3);
	TPM1->CONTROLS[1].CnSC |= (TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK);
	TPM1->CONTROLS[1].CnSC &= ~(TPM_CnSC_MSA_MASK | TPM_CnSC_ELSB_MASK);
	TPM1->CONTROLS[1].CnV = 0;
	PORTB->PCR[1] |= PORT_PCR_MUX(3);
	TPM1->SC |= TPM_SC_CMOD(1);
	TPM2->CONTROLS[0].CnSC |= (TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK);
	TPM2->CONTROLS[0].CnSC &= ~(TPM_CnSC_MSA_MASK | TPM_CnSC_ELSB_MASK);
	TPM2->CONTROLS[0].CnV = 0;
	PORTB->PCR[2] |= PORT_PCR_MUX(3);
	TPM2->SC |= TPM_SC_CMOD(1);
	
}
             